import { FC } from "react";

export const RainbowOverlay: FC<JSX.IntrinsicElements["svg"]> = (props) => (
  <svg
    width="1464"
    height="272"
    viewBox="0 0 1464 272"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <g opacity="0.2">
      <g filter="url(#filter0_f_1_30)">
        <ellipse
          cx="116.937"
          cy="-32.0402"
          rx="188.937"
          ry="102.96"
          fill="#FFC700"
        />
      </g>
      <g filter="url(#filter1_f_1_30)">
        <ellipse
          cx="287.643"
          cy="-32.0402"
          rx="188.937"
          ry="102.96"
          fill="#FF5C00"
        />
      </g>
      <g filter="url(#filter2_f_1_30)">
        <ellipse
          cx="436.804"
          cy="-31.137"
          rx="188.937"
          ry="102.96"
          fill="#FF00B8"
        />
      </g>
      <g filter="url(#filter3_f_1_30)">
        <ellipse
          cx="609.168"
          cy="-31.137"
          rx="188.937"
          ry="102.96"
          fill="#7545FF"
        />
      </g>
      <g filter="url(#filter4_f_1_30)">
        <ellipse
          cx="783.189"
          cy="-31.137"
          rx="188.937"
          ry="102.96"
          fill="#459BFF"
        />
      </g>
      <g filter="url(#filter5_f_1_30)">
        <ellipse
          cx="972.126"
          cy="-31.137"
          rx="188.937"
          ry="102.96"
          fill="#6FEAE2"
        />
      </g>
      <g filter="url(#filter6_f_1_30)">
        <ellipse
          cx="1161.06"
          cy="-31.137"
          rx="188.937"
          ry="102.96"
          fill="#6CD65B"
        />
      </g>
    </g>
    <defs>
      <filter
        id="filter0_f_1_30"
        x="-272"
        y="-335"
        width="777.874"
        height="605.92"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood floodOpacity="0" result="BackgroundImageFix" />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="BackgroundImageFix"
          result="shape"
        />
        <feGaussianBlur
          stdDeviation="100"
          result="effect1_foregroundBlur_1_30"
        />
      </filter>
      <filter
        id="filter1_f_1_30"
        x="-101.294"
        y="-335"
        width="777.874"
        height="605.92"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood floodOpacity="0" result="BackgroundImageFix" />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="BackgroundImageFix"
          result="shape"
        />
        <feGaussianBlur
          stdDeviation="100"
          result="effect1_foregroundBlur_1_30"
        />
      </filter>
      <filter
        id="filter2_f_1_30"
        x="47.8671"
        y="-334.097"
        width="777.874"
        height="605.92"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood floodOpacity="0" result="BackgroundImageFix" />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="BackgroundImageFix"
          result="shape"
        />
        <feGaussianBlur
          stdDeviation="100"
          result="effect1_foregroundBlur_1_30"
        />
      </filter>
      <filter
        id="filter3_f_1_30"
        x="220.231"
        y="-334.097"
        width="777.874"
        height="605.92"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood floodOpacity="0" result="BackgroundImageFix" />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="BackgroundImageFix"
          result="shape"
        />
        <feGaussianBlur
          stdDeviation="100"
          result="effect1_foregroundBlur_1_30"
        />
      </filter>
      <filter
        id="filter4_f_1_30"
        x="394.252"
        y="-334.097"
        width="777.874"
        height="605.92"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood floodOpacity="0" result="BackgroundImageFix" />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="BackgroundImageFix"
          result="shape"
        />
        <feGaussianBlur
          stdDeviation="100"
          result="effect1_foregroundBlur_1_30"
        />
      </filter>
      <filter
        id="filter5_f_1_30"
        x="583.189"
        y="-334.097"
        width="777.874"
        height="605.92"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood floodOpacity="0" result="BackgroundImageFix" />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="BackgroundImageFix"
          result="shape"
        />
        <feGaussianBlur
          stdDeviation="100"
          result="effect1_foregroundBlur_1_30"
        />
      </filter>
      <filter
        id="filter6_f_1_30"
        x="772.126"
        y="-334.097"
        width="777.874"
        height="605.92"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood floodOpacity="0" result="BackgroundImageFix" />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="BackgroundImageFix"
          result="shape"
        />
        <feGaussianBlur
          stdDeviation="100"
          result="effect1_foregroundBlur_1_30"
        />
      </filter>
    </defs>
  </svg>
);
